### ISSUE TITLE
Create view for a singular application

### ISSUE THREAD

**Issue by KevinKristiansen** [Samfundet/Samfundet4#692] opened 2023-09-21 16:33 UTC
There should be a view to see a singular application. Information included here is the application text, detailed information about the applicant, and the positions the applicant have applied for.

**Comment by Snorre98** [comment] 2024-05-09 21:44
Seems to be a duplicate of #670, closing this.
There is a similar page needed, which overviews all applications on a position.

**Closed by Snorre98** 2024-05-09 21:44 UTC
Labels: recruitment
